### ISSUE TITLE
New Tag Needed

### ISSUE THREAD

**Issue by scrahe** [FireMario211/Prism-Menu#47]
A new tag is needed for the repository. "ripoff-of-crystal-client"

**Comment by FireMario211** [comment]
This came out WAY before Crystal's new UI came out. (Look at the dates of when Prism came out vs when Crystal came out for 2.2)

I'm not adding this tag, it is not a "rip off" of Crystal Client.

**Comment by scrahe** [comment]
What are you talking about? The new UI came out TWO MONTHS AGO.
<img width="752" alt="Screen Shot 2024-02-15 at 6 23 07 AM" src="https://github.com/FireMario211/Prism-Menu/assets/55860416/2b356e80-f0f0-45d3-a478-7c419fc94eba">

**Comment by FireMario211** [comment]
I guess I have to get defensive now since you're going to keep going about this.

I was not aware it came out 2 months ago. I wasn't even aware of the new UI while I was working on Prism.

Also the commit you showed in the screenshot is on **December 17th 2023**, I had been working on Prism Menu before that commit came, as shown in this screenshot:
![image](https://github.com/FireMario211/Prism-Menu/assets/17692105/e38698f2-d779-4029-a68c-369d94896adc)
If you want me to provide screenshots that go further back, I can.

In case you want more proof, I could send a file I haven't edited in a while, although considering how pushy you are being about this, I am going to assume you will think I would "spoof the metadata", even when I send proof of it.

Anyways, what makes Prism be a "rip off" of Crystal? Does Crystal have custom theme support? Does Crystal have language support?

If you're saying the UI is ripped off, look side by side at the differences, they're not the exact same. (There are more "categories", the checkboxes are all the way on the right, there are "settings" for hacks, etc)

Incase you want to know what UI inspired me, here is the video:
https://www.youtube.com/watch?v=SbEzc4Dd59Y

Either way, this whole issue is unnecessary, and even if Prism Menu was inspired from Crystal, that doesn't mean it's automatically considered to be a rip off. That's basically saying that all Minecraft Hacked Clients are ripping off of each other, or all GD mod menus are ripping off of each other, or compare MegaHack vs GD. Either way, no one cares, they only want to be able to use the mod menu.

**Comment by scrahe** [comment]
You have a point there, and I'm sorry. Keep working on prism menu. It looks great. (Also I made this issue after putting like 0 thought into it so yeah.)
