### ISSUE TITLE
[Bug]: Switching menu style closes menu

### ISSUE THREAD

**Issue by scrahe** [FireMario211/Prism-Menu#52]
### Platform

Mac OS

### Version

v1.4.2

### Describe the bug

When choosing a new menu style, the menu closes, and the changes are not saved.

### Expected Behavior

It should change the style of the menu, and not close.

### How to reproduce

Open the menu, scroll down to menu style, and change it to ImGui.

### Mods Installed

beat.click-sound.geode
blackholemx.nomoregames.geode
cvolton.betterinfo.geode
firee.PrismMenu.geode
geode.node-ids.geode
geode.texture-loader.geode
ninxout.crystal_client.geode (Disabled)
raydeeux.likebaitexterminator.geode
thesillydoggo.better_startpos_menu.geode

**Comment by FireMario211** [comment]
That's more of a feature than a bug. The reason why the changes aren't saved is because the Mac OS version of Prism Menu does not include ImGUI (as I can't compile with it)
I may even consider hiding the option to change the Menu Style as it currently serves no purpose on Mac OS. That's unless mat fixes the issue with it not being able to be compiled (some pch thing idk)
